# Grafting posterior tree distribution

## Data preparation

### Loading packages

In [1]:
library("TreeTools")
library("phytools")
library("stringr")
library("dispRity")

Le chargement a nécessité le package : ape

Le chargement a nécessité le package : maps


Attachement du package : ‘phytools’


L'objet suivant est masqué depuis ‘package:TreeTools’:

    as.multiPhylo

### Loading data and useful functions

In [2]:
source("function_grafting.r")

In [3]:
tree_multi<-read.tree("../Data_orectolobiformes/posterior_distribution_100_tree_orecto.tree")

In [ ]:
phy<-read.tree("../Data_orectolobiformes/tree_orecto.tree")

In [8]:
fossil_data<-read.table("TS_TE_SP_replicated.tsv", header = TRUE, sep ="\t")

In [18]:
unique(fossil_data$Family)

[1] "Hemiscylliidae"                "Orectolobiformes_incert._fam."
[3] "Brachaeluridae"                "Ginglymostomatidae"
[5] "Orectolobidae"                 "Mesiteiidae"
[7] "Rhincodontidae"                "Parascylliidae"
[9] "Stegostomatidae"

In [ ]:
make_random_fossil_extract <- function(fossil_data, phy){
    
}

In [21]:
fossil_data[fossil_data$Family == "Hemiscylliidae",]

    Order            Family         Genus
1   Orectolobiformes Hemiscylliidae Acanthoscyllium
2   Orectolobiformes Hemiscylliidae Adnetoscyllium
3   Orectolobiformes Hemiscylliidae Almascyllium
25  Orectolobiformes Hemiscylliidae Chiloscyllium
26  Orectolobiformes Hemiscylliidae Chiloscyllium
27  Orectolobiformes Hemiscylliidae Chiloscyllium
28  Orectolobiformes Hemiscylliidae Chiloscyllium
29  Orectolobiformes Hemiscylliidae Chiloscyllium
30  Orectolobiformes Hemiscylliidae Chiloscyllium
31  Orectolobiformes Hemiscylliidae Chiloscyllium
32  Orectolobiformes Hemiscylliidae Chiloscyllium
33  Orectolobiformes Hemiscylliidae Chiloscyllium
34  Orectolobiformes Hemiscylliidae Chiloscyllium
35  Orectolobiformes Hemiscylliidae Chiloscyllium
36  Orectolobiformes Hemiscylliidae Chiloscyllium
37  Orectolobiformes Hemiscylliidae Coelometlaouia
67  Orectolobiformes Hemiscylliidae Hemiscyllium
68  Orectolobiformes Hemiscylliidae Hemiscyllium
69  Orectolobiformes Hemiscylliidae Hemiscyllium
77  Orectolobiformes Hemiscylliidae Notoramphoscyllium
119 Orectolobiformes Hemiscylliidae Pseudospinax
120 Orectolobiformes Hemiscylliidae Pseudospinax
    Species                        Ts        Te       Ts_sd     Te_sd
1   Acanthoscyllium_sahelalmae      85.37120 83.90468 0.6674255 0.7014267
2   Adnetoscyllium_angloparisensis  86.25006 80.21402 0.6675094 0.2980131
3   Almascyllium_cheikheliasi       85.36657 83.92354 0.6303540 0.6051588
25  Chiloscyllium_broennimanni      69.47201 67.75976 2.2957912 2.0060461
26  Chiloscyllium_frequens          86.29027 72.76848 0.4605543 1.1605614
27  Chiloscyllium_gaemersi          74.89527 72.88216 1.3857921 1.5105151
28  Chiloscyllium_grandis           85.21885 83.74857 0.6175605 0.6263321
29  Chiloscyllium_greeni            93.28438 89.49181 0.7193368 0.4778819
30  Chiloscyllium_humboldti         92.20309 91.05933 1.1753910 1.1891869
31  Chiloscyllium_meraense          55.36722 47.68883 0.9655103 2.0485010
32  Chiloscyllium_mereretiae        95.01080 93.85486 0.4543982 0.4546825
33  Chiloscyllium_minutum           61.76057 59.38213 0.5356485 0.6473906
34  Chiloscyllium_missouriense      81.50934 71.64906 2.3154932 1.0888044
35  Chiloscyllium_salvani           58.19371 56.88179 0.8401103 0.9393136
36  Chiloscyllium_vulloi            95.54263 91.07654 0.5655968 0.3944941
37  Coelometlaouia_pannucea         53.24934 39.42155 0.4175240 0.2513160
67  Hemiscyllium_bruxelliensis      53.64009 40.05666 2.2839194 1.0278404
68  Hemiscyllium_hermani            76.75786 61.34165 0.9960733 0.6287580
69  Hemiscyllium_tailledisensis     48.61377 38.36142 2.1761427 0.7803389
77  Notoramphoscyllium_woodwardi    53.40528 39.32839 0.4232432 0.2459726
119 Pseudospinax_heterodon         108.52137 96.99952 1.9475947 1.3185636
120 Pseudospinax_pusillus           97.62262 96.34195 2.2726168 2.0645466

In [20]:
fossil_data[fossil_data$Family == "Ginglymostomatidae",]

    Order            Family             Genus
9   Orectolobiformes Ginglymostomatidae Cantioscyllium
10  Orectolobiformes Ginglymostomatidae Cantioscyllium
11  Orectolobiformes Ginglymostomatidae Cantioscyllium
12  Orectolobiformes Ginglymostomatidae Cantioscyllium
13  Orectolobiformes Ginglymostomatidae Cantioscyllium
14  Orectolobiformes Ginglymostomatidae Cantioscyllium
15  Orectolobiformes Ginglymostomatidae Cantioscyllium
16  Orectolobiformes Ginglymostomatidae Cantioscyllium
17  Orectolobiformes Ginglymostomatidae Cantioscyllium
18  Orectolobiformes Ginglymostomatidae Cantioscyllium
19  Orectolobiformes Ginglymostomatidae Cantioscyllium
42  Orectolobiformes Ginglymostomatidae Delpitoscyllium
43  Orectolobiformes Ginglymostomatidae Delpitoscyllium
50  Orectolobiformes Ginglymostomatidae Ganntouria
52  Orectolobiformes Ginglymostomatidae Ginglymostoma
53  Orectolobiformes Ginglymostomatidae Ginglymostoma
54  Orectolobiformes Ginglymostomatidae Ginglymostoma
55  Orectolobiformes Ginglymostomatidae Ginglymostoma
56  Orectolobiformes Ginglymostomatidae Ginglymostoma
57  Orectolobiformes Ginglymostomatidae Ginglymostoma
58  Orectolobiformes Ginglymostomatidae Ginglymostoma
59  Orectolobiformes Ginglymostomatidae Ginglymostoma
60  Orectolobiformes Ginglymostomatidae Ginglymostoma
61  Orectolobiformes Ginglymostomatidae Ginglymostoma
62  Orectolobiformes Ginglymostomatidae Ginglymostoma
63  Orectolobiformes Ginglymostomatidae Ginglymostoma
64  Orectolobiformes Ginglymostomatidae Ginglymostoma
65  Orectolobiformes Ginglymostomatidae Ginglymostoma
66  Orectolobiformes Ginglymostomatidae Ginglymostoma
71  Orectolobiformes Ginglymostomatidae Hologinglymostoma
74  Orectolobiformes Ginglymostomatidae Nebrius
75  Orectolobiformes Ginglymostomatidae Nebrius
76  Orectolobiformes Ginglymostomatidae Nebrius
109 Orectolobiformes Ginglymostomatidae Plicatoscyllium
110 Orectolobiformes Ginglymostomatidae Plicatoscyllium
111 Orectolobiformes Ginglymostomatidae Plicatoscyllium
112 Orectolobiformes Ginglymostomatidae Plicatoscyllium
113 Orectolobiformes Ginglymostomatidae Plicatoscyllium
114 Orectolobiformes Ginglymostomatidae Plicatoscyllium
115 Orectolobiformes Ginglymostomatidae Plicatoscyllium
116 Orectolobiformes Ginglymostomatidae Protoginglymostoma
117 Orectolobiformes Ginglymostomatidae Pseudoginglymostoma
118 Orectolobiformes Ginglymostomatidae Pseudoginglymostoma
    Species                         Ts          Te         Ts_sd     Te_sd
9   Cantioscyllium_alhaulfi         129.6697289 127.567709 1.1981162 1.1886283
10  Cantioscyllium_bighornensis      89.3547378  71.739696 1.0230549 1.2779080
11  Cantioscyllium_brachyplicatum    99.1546308  97.813702 1.4141812 1.2614764
12  Cantioscyllium_clementsi         78.0995727  76.324100 3.1404692 3.3053163
13  Cantioscyllium_decipiens        100.8023187  86.875133 0.7753498 0.8278541
14  Cantioscyllium_estesi            80.2357114  65.863457 2.5853084 0.7582171
15  Cantioscyllium_hashimiaensis     85.2100824  83.743651 0.6054556 0.5633992
16  Cantioscyllium_lobatum           92.5851997  91.447145 1.3827838 1.4141247
17  Cantioscyllium_markaguntensis    90.1727231  71.195278 0.9057971 2.0136924
18  Cantioscyllium_meyeri            83.9147073  66.638223 0.8645378 1.1245520
19  Cantioscyllium_nessovi           89.6395280  85.285679 1.2518950 1.8183560
42  Delpitoscyllium_africanum        64.8744640  51.488331 1.5147801 2.1026514
43  Delpitoscyllium_planum           64.8933198  61.953646 1.2215073 0.6879879
50  Ganntouria_variabilis            70.1234561  66.066537 1.0801974 0.8836940
52  Ginglymostoma_angolense          54.4449633  39.894550 1.7564716 0.6107399
53  Ginglymostoma_botmaense          72.0553182  65.746483 0.6233908 0.4586007
54  Ginglymostoma_chenanei           58.1457710  56.842097 0.9431386 1.0201791
55  Ginglymostoma_cirratum            0.7382019   0.000000 0.1487042 0.0000000
56  Ginglymostoma_cuspidata          69.2830740  67.657238 1.1689447 1.1148533
57  Ginglymostoma_dartevellei        60.8368857  59.805213 0.8159508 0.8589238
58  Ginglymostoma_delfortriei        23.1475764   2.640664 0.7802540 0.6040308
59  Ginglymostoma_erramii            68.8569748  67.258490 1.3142343 1.3122041
60  Ginglymostoma_khouribgaense      65.9759241  54.851096 1.3613466 0.3965797
61  Ginglymostoma_maghrebianum       52.0761996  49.927984 1.7232338 2.4060368
62  Ginglymostoma_maroccanum         55.3811671  44.709759 1.1317083 3.7646354
63  Ginglymostoma_pectinatum         70.5880743  65.739951 0.7012704 0.4523677
64  Ginglymostoma_serra              22.0534664   8.918012 0.7945563 4.1995897
65  Ginglymostoma_sokotoense         59.4016623  55.581520 0.5355272 0.5964704
66  Ginglymostoma_subafricanum       66.2089421  59.967529 0.5368206 0.8985001
71  Hologinglymostoma_jaegeri        58.5012446  57.214608 0.8213828 0.9297750
74  Nebrius_bequaerti                66.5413958  56.409215 0.7325214 1.0314078
75  Nebrius_obliquus                 56.9766870  31.542768 0.2711218 2.4020460
76  Nebrius_thielensi                55.7143419  38.293768 0.9752194 0.7383419
109 Plicatoscyllium_antiquum         75.3536213  65.998247 4.8619059 0.8194115
110 Plicatoscyllium_derameei         72.3384238  66.104758 0.5809166 0.7919219
111 Plicatoscyllium_gharbii          72.7106390  66.075242 0.4353327 0.6148981
112 Plicatoscyllium_globidens        80.9369032  69.463458 2.3953855 0.5172142
113 Plicatoscyllium_lehneri          71.4752148  65.817218 0.9231853 0.4278633
114 Plicatoscyllium_minutum          71.9987324  65.777223 0.8906688 0.5572713
115 Plicatoscyllium_youssoufiaense   70.4953691  65.782584 0.4802707 0.4230120
116 Protoginglymostoma_ypresiensis   55.2255143  46.868343 1.4658818 0.9368766
117 Pseudoginglymostoma_erguitaense  72.1096155  69.989106 0.6011405 0.5333698
118 Pseudoginglymostoma_idiri        71.1947112  66.613641 1.3664944 0.9627395

In [16]:
fossil_data

    Order            Family                        Genus
1   Orectolobiformes Hemiscylliidae                Acanthoscyllium
2   Orectolobiformes Hemiscylliidae                Adnetoscyllium
3   Orectolobiformes Hemiscylliidae                Almascyllium
4   Orectolobiformes Orectolobiformes_incert._fam. Annea
5   Orectolobiformes Orectolobiformes_incert._fam. Annea
6   Orectolobiformes Orectolobiformes_incert._fam. Annea
7   Orectolobiformes Orectolobiformes_incert._fam. Annea
8   Orectolobiformes Brachaeluridae                Brachaelurid_(gen._nov.)
9   Orectolobiformes Ginglymostomatidae            Cantioscyllium
10  Orectolobiformes Ginglymostomatidae            Cantioscyllium
11  Orectolobiformes Ginglymostomatidae            Cantioscyllium
12  Orectolobiformes Ginglymostomatidae            Cantioscyllium
13  Orectolobiformes Ginglymostomatidae            Cantioscyllium
14  Orectolobiformes Ginglymostomatidae            Cantioscyllium
15  Orectolobiformes Ginglymostomatidae            Cantioscyllium
16  Orectolobiformes Ginglymostomatidae            Cantioscyllium
17  Orectolobiformes Ginglymostomatidae            Cantioscyllium
18  Orectolobiformes Ginglymostomatidae            Cantioscyllium
19  Orectolobiformes Ginglymostomatidae            Cantioscyllium
20  Orectolobiformes Orectolobidae                 Cederstroemia
21  Orectolobiformes Orectolobidae                 Cederstroemia
22  Orectolobiformes Orectolobidae                 Cederstroemia
23  Orectolobiformes Orectolobidae                 Cederstroemia
24  Orectolobiformes Orectolobidae                 Cederstroemia
25  Orectolobiformes Hemiscylliidae                Chiloscyllium
26  Orectolobiformes Hemiscylliidae                Chiloscyllium
27  Orectolobiformes Hemiscylliidae                Chiloscyllium
28  Orectolobiformes Hemiscylliidae                Chiloscyllium
29  Orectolobiformes Hemiscylliidae                Chiloscyllium
30  Orectolobiformes Hemiscylliidae                Chiloscyllium
⋮   ⋮                ⋮                             ⋮
98  Orectolobiformes Rhincodontidae                Palaeorhincodon
99  Orectolobiformes Rhincodontidae                Palaeorhincodon
100 Orectolobiformes Brachaeluridae                Paraginglymostoma
101 Orectolobiformes Orectolobiformes_incert._fam. Parahemiscyllium
102 Orectolobiformes Parascylliidae                Pararhincodon
103 Orectolobiformes Parascylliidae                Pararhincodon
104 Orectolobiformes Parascylliidae                Pararhincodon
105 Orectolobiformes Parascylliidae                Pararhincodon
106 Orectolobiformes Parascylliidae                Pararhincodon
107 Orectolobiformes Parascylliidae                Pararhincodon
108 Orectolobiformes Orectolobiformes_incert._fam. Phorcynis
109 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
110 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
111 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
112 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
113 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
114 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
115 Orectolobiformes Ginglymostomatidae            Plicatoscyllium
116 Orectolobiformes Ginglymostomatidae            Protoginglymostoma
117 Orectolobiformes Ginglymostomatidae            Pseudoginglymostoma
118 Orectolobiformes Ginglymostomatidae            Pseudoginglymostoma
119 Orectolobiformes Hemiscylliidae                Pseudospinax
120 Orectolobiformes Hemiscylliidae                Pseudospinax
121 Orectolobiformes Orectolobidae                 Restesia
122 Orectolobiformes Orectolobidae                 Restesia
123 Orectolobiformes Rhincodontidae                Rhincodon
124 Orectolobiformes Rhincodontidae                Rhincodon
125 Orectolobiformes Orectolobidae                 Squatiscyllium
126 Orectolobiformes Orectolobidae                 Squatiscyllium
127 Orectolobiformes Stegostomatidae               Stegostoma
    Species                              Ts        Te        Ts_sd
1   Acanthoscyllium_sahelalmae            85.37120  83.90468 0.6674255
2   Adnetoscyllium_angloparisensis        86.25006  80.21402 0.6675094
3   Almascyllium_cheikheliasi             85.36657  83.92354 0.6303540
4   Annea_altucuspis                     166.45577 159.72241 0.6055312
5   Annea_carinata                       174.04680 167.76195 1.4440555
6   Annea_maubeugei                      182.59536 176.00677 2.1323804
7   Annea_myriacuspis                    165.88428 163.80670 0.9390416
8   Brachaelurid_(gen._nov.)_roklumensis 130.06684 127.99420 1.2163699
9   Cantioscyllium_alhaulfi              129.66973 127.56771 1.1981162
10  Cantioscyllium_bighornensis           89.35474  71.73970 1.0230549
11  Cantioscyllium_brachyplicatum         99.15463  97.81370 1.4141812
12  Cantioscyllium_clementsi              78.09957  76.32410 3.1404692
13  Cantioscyllium_decipiens             100.80232  86.87513 0.7753498
14  Cantioscyllium_estesi                 80.23571  65.86346 2.5853084
15  Cantioscyllium_hashimiaensis          85.21008  83.74365 0.6054556
16  Cantioscyllium_lobatum                92.58520  91.44714 1.3827838
17  Cantioscyllium_markaguntensis         90.17272  71.19528 0.9057971
18  Cantioscyllium_meyeri                 83.91471  66.63822 0.8645378
19  Cantioscyllium_nessovi                89.63953  85.28568 1.2518950
20  Cederstroemia_havreensis              86.03491  72.77815 0.7573653
21  Cederstroemia_nilsi                   83.11506  81.68592 0.8474532
22  Cederstroemia_siverssoni             113.53649  89.59579 0.7640911
23  Cederstroemia_triangulata             79.24012  71.86848 2.9019693
24  Cederstroemia_ziaensis                85.48125  84.02261 0.5867298
25  Chiloscyllium_broennimanni            69.47201  67.75976 2.2957912
26  Chiloscyllium_frequens                86.29027  72.76848 0.4605543
27  Chiloscyllium_gaemersi                74.89527  72.88216 1.3857921
28  Chiloscyllium_grandis                 85.21885  83.74857 0.6175605
29  Chiloscyllium_greeni                  93.28438  89.49181 0.7193368
30  Chiloscyllium_humboldti               92.20309  91.05933 1.1753910
⋮   ⋮                                    ⋮         ⋮         ⋮
98  Palaeorhincodon_dartevellei           57.11607  48.25730 0.2605462
99  Palaeorhincodon_wardi                 55.33993  40.03957 1.3212574
100 Paraginglymostoma_bloti               69.45049  67.70678 1.7990061
101 Parahemiscyllium_underwoodwardi      138.55435 136.46660 1.0989623
102 Pararhincodon_crochardi               93.06155  71.60763 0.4402451
103 Pararhincodon_germaini                49.15204  38.35102 1.3795401
104 Pararhincodon_groessensi              70.43746  61.71449 1.1103451
105 Pararhincodon_lehmani                106.81371  96.00577 3.1228704
106 Pararhincodon_ornatus                 93.07596  70.81557 0.3940029
107 Pararhincodon_ypresiensis             55.01134  47.67370 1.5795604
108 Phorcynis_catulina                   156.31069 145.71631 1.4123611
109 Plicatoscyllium_antiquum              75.35362  65.99825 4.8619059
110 Plicatoscyllium_derameei              72.33842  66.10476 0.5809166
111 Plicatoscyllium_gharbii               72.71064  66.07524 0.4353327
112 Plicatoscyllium_globidens             80.93690  69.46346 2.3953855
113 Plicatoscyllium_lehneri               71.47521  65.81722 0.9231853
114 Plicatoscyllium_minutum               71.99873  65.77722 0.8906688
115 Plicatoscyllium_youssoufiaense        70.49537  65.78258 0.4802707
116 Protoginglymostoma_ypresiensis        55.22551  46.86834 1.4658818
117 Pseudoginglymostoma_erguitaense       72.10962  69.98911 0.6011405
118 Pseudoginglymostoma_idiri             71.19471  66.61364 1.3664944
119 Pseudospinax_heterodon               108.52137  96.99952 1.9475947
120 Pseudospinax_pusillus                 97.62262  96.34195 2.2726168
121 Restesia_americana                    81.09674  65.46110 2.8760829
122 Restesia_nordquistae                  68.48981  66.88691 1.1553331
123 Rhincodon_ferriolensis                20.30286  15.48995 0.8205900
124 Rhincodon_typus                       33.04987   0.00000 6.2303852
125 Squatiscyllium_casieri                52.84596  50.89581 1.9750968
126 Squatiscyllium_nigeriensis            59.17387  51.74622 0.5344202
127 Stegostoma_tethysiensis               40.59213  38.77285 1.3828666
    Te_sd
1   0.7014267
2   0.2980131
3   0.6051588
4   1.4609423
5   0.6223649
6   2.4723321
7   0.9581897
8   1.1913003
9   1.1886283
10  1.2779080
11  1.2614764
12  3.3053163
13  0.8278541
14  0.7582171
15  0.5633992
16  1.4141247
17  2.0136924
18  1.1245520
19  1.8183560
20  1.5396034
21  0.7892322
22  0.5096808
23  1.2024209
24  0.5529079
25  2.0060461
26  1.1605614
27  1.5105151
28  0.6263321
29  0.4778819
30  1.1891869
⋮   ⋮
98  2.5741803
99  1.1356733
100 1.5679246
101 1.1976154
102 1.2298158
103 0.7730940
104 0.7872967
105 1.2238262
106 0.3816539
107 1.5359188
108 2.0163549
109 0.8194115
110 0.7919219
111 0.6148981
112 0.5172142
113 0.4278633
114 0.5572713
115 0.4230120
116 0.9368766
117 0.5333698
118 0.9627395
119 1.3185636
120 2.0645466
121 0.5245405
122 1.0849179
123 1.5562150
124 0.0000000
125 2.6226426
126 3.4338390
127 0.5867023

## Grafting 1,000 replicates for the consensus tree

In [ ]:
multi_tree<-function(tree, fossil_data, taxonomy, output){
phylo_list<-list()
class(phylo_list)<-"multiPhylo"
       for(i in 1:1000){
           
            temp_tree<-tree
           
            taxo_eoetmopterus_supracretaceus<-extract.clade(temp_tree, getMRCA(temp_tree, c("Etmopterus_sheikoi", "Aculeola_nigra")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Eoetmopterus_supracretaceus", taxo_eoetmopterus_supracretaceus, 1)

            phylo_list[[i]]<-temp_tree
       }
    write.nexus(phylo_list, file = output)
}

## Saving the multi tree filem

In [ ]:
multi_tree(phy, fossil_data, table_trait, "../../raw_data/Multi_Squaliformes_fossil_consensus_distribution.tree")

## Grafting fossils on the posterior tree distribution

In [ ]:
multi_tree_posterior<-function(tree, fossil_data, taxonomy, output){
phylo_list<-list()
class(phylo_list)<-"multiPhylo"
       for(i in 1:100){
           
            temp_tree<-extract.clade(tree[[i]], getMRCA(tree[[i]], c("Squalus_acanthias", "Etmopterus_princeps")))

            taxo_eoetmopterus_supracretaceus<-extract.clade(temp_tree, getMRCA(temp_tree, c("Etmopterus_sheikoi", "Aculeola_nigra")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Eoetmopterus_supracretaceus", taxo_eoetmopterus_supracretaceus, 1)

            taxo_isistius_trituratus<-c("Isistius_brasiliensis")
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Isistius_trituratus", taxo_isistius_trituratus, 1)
           
            taxo_protocentrophorus_balticus<-extract.clade(temp_tree, getMRCA(temp_tree, c("Deania_calcea", "Centrophorus_squamosus", "Centrophorus_granulosus")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Protocentrophorus_balticus", taxo_protocentrophorus_balticus, 1)
            
            taxo_protosqualus_albertsi<-extract.clade(temp_tree, getMRCA(temp_tree, c("Squalus_acanthias", "Cirrhigaleus_barbifer", "Squalus_cubensis")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Protosqualus_albertsi", taxo_protosqualus_albertsi, 1)

            taxo_protosqualus_sigei<-extract.clade(temp_tree, getMRCA(temp_tree, c("Squalus_acanthias", "Cirrhigaleus_barbifer", "Squalus_cubensis")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Protosqualus_sigei", taxo_protosqualus_sigei, 1)

            taxo_squalus_minor<-extract.clade(temp_tree, getMRCA(temp_tree, c("Squalus_acanthias", "Cirrhigaleus_barbifer", "Squalus_cubensis")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Squalus_minor", taxo_squalus_minor, 1)

            taxo_trigonognathus_virginiae<-c("Trigonognathus_kabeyai")
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Trigonognathus_virginiae", taxo_trigonognathus_virginiae, 1)

            taxo_eodalatias_crenulatus<-c("Dalatias_licha")
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Eodalatias_crenulatus", taxo_eodalatias_crenulatus, 1)

            taxo_squalidalatias_savoiei<-extract.clade(temp_tree, getMRCA(temp_tree, c("Dalatias_licha", "Isistius_brasiliensis")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Squaliodalatias_savoiei", taxo_squalidalatias_savoiei, 1)

            taxo_proetmopterus_hemmooriensis<-extract.clade(temp_tree, getMRCA(temp_tree, c("Etmopterus_sheikoi", "Etmopterus_princeps", "Etmopterus_polli")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Proetmopterus_hemmooriensis", taxo_proetmopterus_hemmooriensis, 1)

            taxo_cretascymnus_westfalicus<-extract.clade(temp_tree, getMRCA(temp_tree, c("Somniosus_microcephalus", "Rhinoscymnus_rostratus")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Cretascymnus_westfalicus", taxo_cretascymnus_westfalicus, 1)

            taxo_cretascymnus_adonis<-extract.clade(temp_tree, getMRCA(temp_tree, c("Somniosus_microcephalus", "Rhinoscymnus_rostratus")))$tip.label
            temp_tree<-tree_grafting_manual(temp_tree, fossil_data, "Cretascymnus_adonis", taxo_cretascymnus_adonis, 1)
            phylo_list[[i]]<-temp_tree
       }
    write.tree(phylo_list, file = output)
}

## Saving the 100 grafted trees

In [ ]:
multi_tree_posterior(tree, fossil_data, table_trait, "../../raw_data/Multi_Squaliformes_fossil_posterior_distribution.tree")