# Make data for BioGeoBEARS

## Loading packages

In [13]:
library("tidygraph")
library("igraph")
library("ggraph")
library("tidyverse")
library("ape")

Attachement du package : ‘ape’


L'objet suivant est masqué depuis ‘package:dplyr’:

    where


Les objets suivants sont masqués depuis ‘package:igraph’:

    degree, edges, mst, ring

## Loading data

In [2]:
table <- read.table("../Data_orectolobiformes/Time_periods.tsv", sep ="\t", header = TRUE)

In [ ]:
table_biogeo <- read.table("../Data_orectolobiformes/Biogeography extant.tsv", sep ="\t", header = TRUE)

In [14]:
phy <- read.tree("../Data_orectolobiformes/tree_orecto.tree")

In [17]:
table_biogeo[gsub(" ", "_", table_biogeo$Species) %in% phy$tip.label, ]

   Family             Genus               Species
1  Brachaeluridae     Brachaelurus        Brachaelurus colcloughi
2  Brachaeluridae     Brachaelurus        Brachaelurus waddi
3  Hemiscyliidae      Chiloscyllium       Chiloscyllium arabicum
4  Hemiscyliidae      Chiloscyllium       Chiloscyllium burmensis
5  Hemiscyliidae      Chiloscyllium       Chiloscyllium griseum
6  Hemiscyliidae      Chiloscyllium       Chiloscyllium hasseltii
7  Hemiscyliidae      Chiloscyllium       Chiloscyllium indicum
8  Hemiscyliidae      Chiloscyllium       Chiloscyllium plagiosum
9  Hemiscyliidae      Chiloscyllium       Chiloscyllium punctatum
11 Parascylliidae     Cirrhoscyllium      Cirrhoscyllium formosanum
13 Orectolobidae      Eucrossorhinus      Eucrossorhinus dasypogon
14 Ginglymostomatidae Ginglymostoma       Ginglymostoma cirratum
15 Ginglymostomatidae Ginglymostoma       Ginglymostoma unami
17 Hemiscyliidae      Hemiscyllium        Hemiscyllium galei
18 Hemiscyliidae      Hemiscyllium        Hemiscyllium hallstromi
19 Hemiscyliidae      Hemiscyllium        Hemiscyllium halmahera
20 Hemiscyliidae      Hemiscyllium        Hemiscyllium henryi
21 Hemiscyliidae      Hemiscyllium        Hemiscyllium michaeli
22 Hemiscyliidae      Hemiscyllium        Hemiscyllium ocellatum
23 Hemiscyliidae      Hemiscyllium        Hemiscyllium strahani
24 Hemiscyliidae      Hemiscyllium        Hemiscyllium trispeculare
25 Ginglymostomatidae Nebrius             Nebrius ferrugineus
26 Orectolobidae      Orectolobus         Orectolobus floridus
27 Orectolobidae      Orectolobus         Orectolobus halei
28 Orectolobidae      Orectolobus         Orectolobus hutchinsi
29 Orectolobidae      Orectolobus         Orectolobus japonicus
30 Orectolobidae      Orectolobus         Orectolobus leptolineatus
31 Orectolobidae      Orectolobus         Orectolobus maculatus
32 Orectolobidae      Orectolobus         Orectolobus ornatus
33 Orectolobidae      Orectolobus         Orectolobus parvimaculatus
34 Orectolobidae      Orectolobus         Orectolobus reticulatus
35 Orectolobidae      Orectolobus         Orectolobus wardi
36 Parascylliidae     Parascyllium        Parascyllium collare
38 Parascylliidae     Parascyllium        Parascyllium ferrugineum
41 Ginglymostomatidae Pseudoginglymostoma Pseudoginglymostoma brevicaudatum
42 Rhincodontidae     Rhincodon           Rhincodon typus
44 Orectolobidae      Sutorectus          Sutorectus tentaculatus
   East.Pacific West.Atlantic East.Atlantic Tethys West.Indo.Pacific
1  0            0             0             0      0
2  0            0             0             0      0
3  0            0             0             0      1
4  0            0             0             0      1
5  0            0             0             0      1
6  0            0             0             0      0
7  0            0             0             0      1
8  0            0             0             0      1
9  0            0             0             0      1
11 0            0             0             0      0
13 0            0             0             0      0
14 0            1             1             0      0
15 1            0             0             0      0
17 0            0             0             0      0
18 0            0             0             0      0
19 0            0             0             0      0
20 0            0             0             0      0
21 0            0             0             0      0
22 0            0             0             0      0
23 0            0             0             0      0
24 0            0             0             0      0
25 0            0             0             0      1
26 0            0             0             0      0
27 0            0             0             0      0
28 0            0             0             0      0
29 0            0             0             0      0
30 0            0             0             0      0
31 0            0             0             0      0
32 0            0             0             0      0
33 0            0             0             0      0
34 0            0             0             0      0
35 0            0             0             0      0
36 0            0             0             0      0
38 0            0             0             0      0
41 0            0             0             0      1
42 1            1             1             0      1
44 0            0             0             0      0
   Central.Indo.Pacific Australasia
1  0                    1
2  0                    1
3  0                    0
4  0                    0
5  1                    0
6  1                    0
7  1                    0
8  1                    0
9  1                    1
11 1                    0
13 0                    1
14 0                    0
15 0                    0
17 0                    1
18 1                    0
19 0                    1
20 0                    1
21 0                    1
22 0                    1
23 0                    1
24 0                    1
25 1                    1
26 0                    1
27 0                    1
28 0                    1
29 1                    0
30 1                    0
31 0                    1
32 0                    1
33 0                    1
34 0                    1
35 0                    1
36 0                    1
38 0                    1
41 0                    0
42 1                    1
44 0                    1

In [ ]:
table_biogeo

In [12]:
cbind(gsub(as.matrix((apply(X = table_biogeo[,c(4:10)], MARGIN = 1, FUN = paste, collapse = "")))

      [,1]
 [1,] 0000001
 [2,] 0000001
 [3,] 0000100
 [4,] 0000100
 [5,] 0000110
 [6,] 0000010
 [7,] 0000110
 [8,] 0000110
 [9,] 0000111
[10,] 0000010
[11,] 0000010
[12,] 0000010
[13,] 0000001
[14,] 0110000
[15,] 1000000
[16,] 0000001
[17,] 0000001
[18,] 0000010
[19,] 0000001
[20,] 0000001
[21,] 0000001
[22,] 0000001
[23,] 0000001
[24,] 0000001
[25,] 0000111
[26,] 0000001
[27,] 0000001
[28,] 0000001
[29,] 0000010
[30,] 0000010
[31,] 0000001
[32,] 0000001
[33,] 0000001
[34,] 0000001
[35,] 0000001
[36,] 0000001
[37,] 0000001
[38,] 0000001
[39,] 0000001
[40,] 0000001
[41,] 0000100
[42,] 1110111
[43,] 0000111
[44,] 0000001

## Prepare biogeographic data for extant taxa

In [7]:
table_biogeo <- read.table("../Data_orectolobiformes/Biogeography extant.tsv", sep ="\t", header = TRUE)

## Creating function to clean and save data

In [3]:
make_table_BioGeoBEARS <- function(time_periods_table, prefix){
    temp_length <- (ncol(time_periods_table) - 2)
    table_adjacency <- c()
    table_dispersal <- c()
    temp_mat_adj <- matrix(0, temp_length, temp_length)
    for(i in 1:nrow(time_periods_table)){
        temp_mat_adj <- matrix(0, temp_length, temp_length)
        temp_period_table <- time_periods_table[i, c(3:ncol(time_periods_table))]
        from <- c()
        to <- c()
        
        for(j in 1:temp_length){
            if(temp_period_table[j] != "0"){
                temp_mat_adj[j,eval(parse(text = temp_period_table[j]))] <- 1
                from <- c(from, rep(j,length(eval(parse(text = temp_period_table[j])))))
                to <- c(to, eval(parse(text = temp_period_table[j])))
            }
        }
        
        nodes <- tibble(id = 1:temp_length)
        edges <- tibble(from = from, to = to)
        
        temp_data_from <- edges[edges[,1] != edges[,2],]

        temp_data_to_1 <- edges[edges[,1] != edges[,2],]

        temp_data_to_2 <- edges[edges[,1] != edges[,2],]

        colnames(temp_data_to_1) <- c("to", "to_2")

        colnames(temp_data_to_2) <- c("to_2", "to_3")

        temp_data_03 <- merge(temp_data_from, temp_data_to_1, by = "to")
        temp_data_03 <- temp_data_03[temp_data_03[,2] != temp_data_03[,3],]

        temp_data_04 <- merge(temp_data_03, temp_data_to_1, by = "to_2")
        temp_data_04 <- temp_data_04[temp_data_04[,3] != temp_data_04[,4],]

        temp_mat_dispersal <- matrix(0.001, 7, 7)
        
        temp_data_direct <- as.matrix(edges)
        
        for(k in 1:nrow(temp_data_direct)){
            if(temp_data_direct[k,1] == temp_data_direct[k,2]){
                temp_mat_dispersal[temp_data_direct[k,1], temp_data_direct[k,2]] <- 1 
            }
            if(temp_data_direct[k,1] != temp_data_direct[k,2]){
                temp_mat_dispersal[temp_data_direct[k,1], temp_data_direct[k,2]] <- 0.5
            }
        
        }

        for(k in 1:nrow(temp_data_03)){
            if(temp_mat_dispersal[temp_data_03[k,2], temp_data_03[k,3]] == 0.0000001){
                temp_mat_dispersal[temp_data_03[k,2], temp_data_03[k,3]] <- 0.25
            }
        }

        for(k in 1:nrow(temp_data_04)){
            if(temp_mat_dispersal[temp_data_04[k,3], temp_data_04[k,4]] == 0.0000001){
                temp_mat_dispersal[temp_data_04[k,3], temp_data_04[k,4]] <- 0.125
            }
        }
        
        
        my_graph <- tbl_graph(nodes = nodes, edges = edges, directed = FALSE)
        
        connectivity_graph <-ggraph(my_graph, layout = "stress") +
            geom_edge_link() +
            geom_node_point(size = 10, colour = "antiquewhite") +
            geom_node_text(aes(label = id)) +
            theme_graph()
        
        ggsave(paste("Connection/connection_grap_", as.character(time_periods_table[i,2]), ".pdf",sep = ""))
        
        table_adjacency <- rbind(table_adjacency, LETTERS[1:7], temp_mat_adj, matrix(data=" ", ncol=7, nrow=1))
        
        table_dispersal <- rbind(table_dispersal, LETTERS[1:7], temp_mat_dispersal, matrix(data=" ", ncol=7, nrow=1))
    }
    table_adjacency <- rbind(table_adjacency, cbind("END", matrix(data = " ", ncol=6, nrow=1)))
    table_dispersal <- rbind(table_dispersal, cbind("END", matrix(data = " ", ncol=6, nrow=1)))
    write.table(time_periods_table[,2], paste(prefix, "_time_period.txt", sep = ""), sep ="\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
    write.table(table_adjacency, paste(prefix, "_area_matrix.txt", sep = ""), sep ="\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
    write.table(table_dispersal, paste(prefix, "_dispersal_matrix.txt", sep = ""), sep ="\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
}

## Execute function

In [4]:
data <- make_table_BioGeoBEARS(table, "7_area")

Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image
Saving 6.67 x 6.67 in image